.flake8
.github/pull_request_template.md
.gitignore
.pre-commit-config.yaml
Readme.md
pyproject.toml
requirements/dev.txt
requirements/prod.txt
src/handlers/helloWorldHandler.py
src/service/helloWorld.py
src/tests/handlers/helloWorldHandler_test.py
src/tests/service/helloWorld_test.py

**Description**
Actually the project doesn't have any configuration or code base.
**Solution**
Added basic configuration to execute unit tests, lint code and pre-commit validations.

feat: KPI-11 Create base project for BackEnd

---

.gitignore
src/service/helloWorld.py

feat: KPI-0 Testing lambda changes

---

.github/workflows/cd-kpinetwork-backend.yml
.github/workflows/ci-kpinetwork-backend.yml
infrastructure/.terraform.lock.hcl
infrastructure/modules.tf
infrastructure/sql/output.tf
infrastructure/sql/rds.tf
infrastructure/sql/variables.tf
infrastructure/variables.tf
infrastructure/vpc/output.tf
infrastructure/vpc/security_groups.tf
infrastructure/vpc/subnets.tf
infrastructure/vpc/variables.tf
infrastructure/vpc/vpc.tf

feat: KPI 17 create db instance with vpc config

---

db/migrations/versions/220f0c0497b4_create_first_db_schema.py
infrastructure/modules.tf
infrastructure/policy/iam.tf
infrastructure/policy/variables.tf

fix: KPI-30 fix code build role

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/company/get_revenue_sum_by_company_handler.py
src/service/company/company_service.py
src/tests/service/company/company_service_test.py
src/tests/utils/query_builder_test.py
src/utils/query_builder.py

feat: KPI-58-revenue-sum-by-company

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/cohort/get_cohort_by_id_handler.py
src/handlers/cohort/get_cohort_scenarios_handler.py
src/handlers/cohort/get_cohorts_handler.py
src/service/cohort/cohort_service.py
src/tests/service/cohort/cohort_service_test.py
src/tests/service/financial_scenario/financial_scenario_service_test.py

feat: KPI-55 create lambda to retrieve cohorts

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/cohort/get_revenue_sum_by_cohort_handler.py
src/handlers/metrics/get_average_metrics_handler.py
src/service/cohort/cohort_service.py
src/service/company/company_service.py
src/service/metrics/metrics_service.py
src/tests/service/cohort/cohort_service_test.py
src/tests/service/metrics/metrics_service_test.py
src/tests/utils/query_builder_test.py
src/tests/utils/response_sql_test.py
src/utils/query_builder.py
src/utils/response_sql.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-63)

feat: KPI-63 add lambdas for metric average and cohort sum revenue

---

db/migrations/versions/4f7b7144cffa_size_cohort_in_company.py

feat: KPI-00 add size cohort in company table

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/company/get_growth_and_margin_hanlder.py
src/service/company/company_service.py
src/tests/service/company/company_service_test.py
src/tests/utils/response_sql_test.py
src/utils/response_sql.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-67)

feat: KPI-67 create growth and margin lambda

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/company/get_expected_growth_and_margin_handler.py
src/service/company/company_service.py
src/tests/service/company/company_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-69)

feat: KPI-69 create expected growth and margin lambda

---

src/handlers/universe_overview/get_universe_overview_handler.py
src/service/financial_scenario/financial_scenario_service.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-81)

feat: KPI-81 CORS configuration in Universe Overview handler

---

infrastructure/cognito/cognito.tf
infrastructure/cognito/outputs.tf
infrastructure/cognito/variables.tf
infrastructure/modules.tf

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-45)

feat: KPI-45 Create users pool in Cognito

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/cognito/cognito.tf
infrastructure/cognito/outputs.tf
infrastructure/cognito/variables.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/functions/variables.tf
infrastructure/logs/cloudwatch.tf
infrastructure/modules.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/policy/variables.tf
infrastructure/variables.tf
manifest.yml
requirements/lambda_layer/requirements.txt
src/handlers/post_confirmation_trigger/add_user_to_customer_group_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-88)

feat: KPI-88 create lambda and add trigger in user pool

---

src/handlers/comparison_vs_peers/get_comparison_vs_peers_handler.py
src/service/company_report_vs_peers/company_report_vs_peers.py
src/service/comparison_vs_peers/comparison_vs_peers.py
src/tests/service/company_report_vs_peers/company_report_vs_peers_test.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py
src/tests/utils/response_sql_test.py
src/utils/response_sql.py

feat: KPI-91 refactor rule of 40

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/cognito/cognito.tf
infrastructure/cognito/variables.tf
infrastructure/functions/lambda.tf
infrastructure/functions/layer.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/modules.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/pre_signup_trigger/verify_users_with_same_email_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-93)

feat: KPI-93 add lambda trigger in cognito to avoid duplicate users

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/users/get_users_handler.py
src/service/users/users_service.py
src/tests/service/users/users_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-103)

feat: KPI-103 create lambda to get users from cognito

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/modules.tf
infrastructure/network/gateways.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/policy/variables.tf
infrastructure/variables.tf
manifest.yml
src/handlers/users/get_roles_handler.py
src/service/users/users_service.py
src/tests/service/users/users_service_test.py

feat: KPI-104 get roles

---

src/handlers/company/get_all_companies_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-112)

feat: KPI-112 enable CORS in companies endpoint

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/user_details/get_user_details_handler.py
src/handlers/users/get_users_handler.py
src/service/user_details/user_details_service.py
src/service/users/users_service.py
src/tests/service/user_details/user_details_service_test.py
src/tests/service/users/users_service_test.py
src/tests/utils/response_user_test.py
src/utils/response_user.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-97)

feat: KPI-97 user details lambda

---

casbin_configuration/policy_manager.py
infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/functions/variables.tf
infrastructure/logs/cloudwatch.tf
infrastructure/modules.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/company/change_company_publicly_handler.py
src/handlers/user_details/assign_company_permissions_handler.py
src/handlers/user_details/get_company_permissions_handler.py
src/handlers/user_details/get_user_details_handler.py
src/handlers/user_details/get_user_details_service.py
src/service/user_details/user_details_service.py
src/tests/service/user_details/user_details_service_test.py

feat: KPI-98 get user company permissions resources

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/company/get_all_public_companies_handler.py
src/service/company/company_service.py
src/service/company_report_vs_peers/company_report_vs_peers.py
src/service/comparison_vs_peers/comparison_vs_peers.py
src/service/universe_overview/universe_overview_service.py
src/tests/service/company/company_service_test.py
src/tests/service/company_report_vs_peers/company_report_vs_peers_test.py
src/utils/query_builder.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-113)

feat: KPI 113 verify and get public companies

---

infrastructure/functions/lambda.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
manifest.yml
src/handlers/company/change_company_publicly_handler.py
src/handlers/company/get_all_companies_handler.py
src/handlers/company/get_all_public_companies_handler.py
src/handlers/company/get_company_handler.py
src/handlers/company_report_vs_peers/get_company_report_vs_peers_handler.py
src/handlers/comparison_vs_peers/get_comparison_vs_peers_handler.py
src/handlers/universe_overview/get_universe_overview_handler.py
src/service/company/company_service.py
src/service/company_report_vs_peers/company_report_vs_peers.py
src/service/comparison_vs_peers/comparison_vs_peers.py
src/service/universe_overview/universe_overview_service.py
src/tests/service/company/company_service_test.py
src/tests/service/company_report_vs_peers/company_report_vs_peers_test.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py
src/tests/service/universe_overview/universe_overview_service_test.py
src/tests/utils/company_anonymization_test.py
src/utils/company_anonymization.py
src/utils/verify_user_permissions.py

feat: KPI-99 modify queries to hide company information

---

src/service/company/company_service.py
src/service/comparison_vs_peers/comparison_vs_peers.py
src/tests/service/company/company_service_test.py
src/tests/utils/company_anonymization_test.py
src/utils/company_anonymization.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-118)

feat: KPI-118 retrieve companies for user permissions

---

infrastructure/network/gateways.tf
src/handlers/comparison_vs_peers/get_comparison_vs_peers_handler.py
src/service/comparison_vs_peers/comparison_vs_peers.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py

feat: KPI-115 refactor comparison vs peers

---

.pre-commit-config.yaml
db/migrations/versions/143ff6eab726_add_ranges_column.py
manifest.yml
requirements/envs/dev.txt
requirements/envs/prod.txt
src/handlers/comparison_vs_peers/get_comparison_vs_peers_handler.py
src/service/comparison_vs_peers/comparison_vs_peers.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py
src/tests/utils/revenue_range_test.py
src/utils/revenue_range.py

feat: KPI-120 revenue ranges

---

db/migrations/versions/c36c65c78855_alter_margin_column_in_company_table.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-132)

feat: KPI-132 alter margin column in company table

---

src/service/comparison_vs_peers/comparison_vs_peers_service.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-146)

feat: KPI-146 revenue with permissions

---

src/handlers/universe_overview/get_universe_overview_handler.py
src/service/comparison_vs_peers/comparison_vs_peers_service.py
src/service/universe_overview/universe_overview_service.py
src/tests/handlers/universe_overview/get_universe_overview_handler_test.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py
src/tests/service/universe_overview/universe_overview_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-141)

 feat: KPI- 141 calculate rule of 40

---

manifest.yml
src/handlers/universe_overview/get_universe_overview_handler.py
src/service/calculator/calculator_repository.py
src/service/calculator/calculator_service.py
src/service/company_report_vs_peers/company_report_vs_peers_service.py
src/service/comparison_vs_peers/comparison_vs_peers_service.py
src/service/universe_overview/universe_overview_service.py
src/tests/handlers/universe_overview/get_universe_overview_handler_test.py
src/tests/service/calculator/calculator_repository_test.py
src/tests/service/universe_overview/universe_overview_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-143)

feat: KPI-143 144 universe overview metric calculations

---

Readme.md
local_file_compression.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-133)

feat: KPI-133 create local zip generator

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/layer.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/upload_data/upload_data_s3_trigger_handler.py
src/handlers/upload_file/upload_file_s3_handler.py
src/tests/data/sample_event_upload_data.json
src/tests/handlers/upload_data/upload_data_s3_trigger_handler_test.py
src/tests/handlers/upload_file/upload_file_s3_handler_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-148)

feat: KPI-148 create endpoint to upload file to S3

---

etl/glue.md
etl/kpinetwork_analizer.py
infrastructure/sql/rds.tf
src/handlers/upload_file/upload_file_s3_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-135)

refactor: KPI-135 refactor etl job code with new requeriments

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/functions/variables.tf
infrastructure/logs/cloudwatch.tf
infrastructure/modules.tf
infrastructure/network/outputs.tf
infrastructure/network/websocket.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/policy/variables.tf
infrastructure/sql/rds.tf
infrastructure/variables.tf
manifest.yml
src/handlers/websocket/connect.py
src/handlers/websocket/disconnect.py
src/handlers/websocket/message.py
src/tests/data/sample_event_websocket.json
src/tests/handlers/upload_file/upload_file_s3_handler_test.py
src/tests/handlers/websocket/message_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-151)

feat: KPI-151 websocket infrastructure

---

src/service/calculator/calculator_repository.py
src/service/comparison_vs_peers/comparison_vs_peers_service.py
src/service/universe_overview/universe_overview_service.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py
src/tests/service/universe_overview/universe_overview_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-150)
- [ x] Feature (Issue from an Active Sprint)
- [x ] Unit Test.
- [x ] Coverage.

feat: KPI-150 modify filters for size cohort and growth profile

---

db/migrations/versions/80253de57d77_remove_fields_from_company.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-135)

feat: KPI-135 remove unused fields in company

---

db/migrations/versions/048dd8a08bdf_connection_id_table.py
etl/kpinetwork_analizer.py
src/service/comparison_vs_peers/comparison_vs_peers_service.py
src/service/universe_overview/universe_overview_service.py
src/utils/profile_range.py

feat: KPI-60 create connection websocket table

---

src/handlers/websocket/register.py

fix: KPI-60 register websocket delete encode

---

infrastructure/variables.tf
manifest.yml
src/handlers/upload_file/validate_data_handler.py
src/service/upload_file/preview_data_validation_service.py
src/tests/handlers/upload_file/validate_data_handler_test.py
src/tests/service/upload_file/preview_data_validation_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-153)

feat: KPI-153 modify preview validation service

---

src/handlers/authorizer/authorize_handler.py
src/handlers/company/change_company_publicly_handler.py
src/handlers/company/get_all_companies_handler.py
src/handlers/company/get_all_public_companies_handler.py
src/handlers/company/get_company_handler.py
src/handlers/company_report_vs_peers/get_company_report_vs_peers_handler.py
src/handlers/comparison_vs_peers/download_comparison_vs_peers_handler.py
src/handlers/comparison_vs_peers/get_comparison_vs_peers_handler.py
src/handlers/glue/glue_trigger_handler.py
src/handlers/post_confirmation_trigger/add_user_to_customer_group_handler.py
src/handlers/pre_signup_trigger/verify_users_with_same_email_handler.py
src/handlers/universe_overview/get_universe_overview_handler.py
src/handlers/user_details/assign_company_permissions_handler.py
src/handlers/user_details/change_user_role_handler.py
src/handlers/user_details/get_company_permissions_handler.py
src/handlers/user_details/get_user_details_handler.py
src/handlers/users/get_roles_handler.py
src/handlers/users/get_users_handler.py
src/handlers/users/get_users_service_instance.py
src/handlers/websocket/connect.py
src/handlers/websocket/disconnect.py
src/handlers/websocket/message.py
src/service/company/company_service.py
src/service/glue/glue_service.py
src/service/universe_overview/universe_overview_service.py
src/tests/handlers/users/get_roles_handler_test.py
src/tests/handlers/users/get_users_handler_test.py
src/tests/handlers/users/get_users_service_instance_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-131)
- [ x ] Feature (Issue from an Active Sprint)
- [x ] Unit Test.
- [x ] Coverage.

feat: KPI-131 Add comments in empty function

---

db/migrations/versions/051ca978f7ec_create_investment_table.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-174)

feat: KPI-174 create investment and investor tables

---

.github/workflows/cd-kpinetwork-backend.yml
.github/workflows/ci-demo-kpinetwork-backend.yml
.github/workflows/demo-kpinetwork-backend.yml
src/service/investment_peers_report/investment_repository.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-177)

fix: KPI-177 fix issue with base year of report

---

src/service/investment_peers_report/investment_repository.py
src/tests/service/investment_peers_report/investment_repository_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-185)

test: KPI-185 increase coverage

---

infrastructure/network/gateways.tf
src/handlers/edit_modify/edit_data_handler.py
src/handlers/edit_modify/get_edit_modify_data_handler.py
src/service/edit_modify/edit_service.py
src/tests/data/sample_event_edit_modify.json
src/tests/service/edit_modify/edit_service_test.py
src/tests/utils/commons_functions_test.py
src/utils/commons_functions.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-194)

feat: KPI-194 add filters to edit modify

---

manifest.yml
src/exceptions/base_exception.py
src/handlers/glue/glue_trigger_handler.py
src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/service/glue/glue_service.py
src/service/user_details/user_details_service.py
src/tests/service/glue/glue_service_test.py
src/tests/service/scenario/delete_scenarios_service_test.py
src/utils/query_builder.py
src/utils/verify_user_permissions.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-125)

refactor: KPI-125 sonar cloud fix

---

manifest.yml
src/handlers/company/get_all_companies_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-193)

feat: KPI-193 change get all companies max count

---

src/service/company_details/company_details_service.py
src/tests/service/company_details/company_details_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-197)

fix: KPI-197 add investments to delete records query

---

src/service/edit_modify/edit_service.py

fix: KPI-000 fix scenarios filter get edit modify

---

manifest.yml
src/handlers/edit_modify/edit_data_handler.py
src/handlers/scenario/add_scenario_handler.py
src/service/scenario/scenario_service.py
src/tests/service/scenario/scenario_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-205)

feat: KPI-205 refactor add scenarios

---

src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/tests/service/by_metric_report/metric_report_repository_test.py
src/utils/profile_range.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-200)

refactor: KPI-200 refactor of metric report

---

src/service/by_metric_report/metric_report_repository.py

fix: KPI-00 fix actuals vs budget metrics

---

db/migrations/versions/82d43584a2b7_create_metric_sort_table.py

feat: KPI-216 create metric sort table

---

src/service/edit_modify/edit_service.py
src/service/scenario/scenario_service.py
src/tests/service/edit_modify/edit_service_test.py
src/utils/query_builder.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-224)

fix: KPI-224 fix edit modify bug - repeated metric id in query

---

src/handlers/comparison_vs_peers/download_comparison_vs_peers_handler.py
src/service/calculator/calculator_report.py
src/service/comparison_vs_peers/comparison_vs_peers_service.py
src/service/investment_peers_report/investment_repository.py
src/service/investment_peers_report/investment_year_report.py
src/tests/service/calculator/calculator_report_test.py
src/tests/service/comparison_vs_peers/comparison_vs_peers_test.py
src/tests/service/investment_peers_report/investment_year_report_test.py
src/utils/profile_range.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-201)

feat: KPI-201 add new metric in the investment repository

---

infrastructure/network/gateways.tf
src/handlers/dynamic_report/get_dynamic_report_handler.py
src/service/calculator/calculator_repository.py
src/service/dynamic_report/dynamic_report.py
src/service/investment_peers_report/investment_repository.py
src/tests/service/dynamic_report/dynamic_report_test.py
src/tests/service/investment_peers_report/investment_repository_test.py
src/utils/profile_range.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-220)

feat: KPI-220 refactor dynamic report

---

src/handlers/company_details/get_company_details_handler.py
src/service/company_details/company_details_service.py
src/tests/service/company_details/company_details_service_test.py
src/utils/app_names.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-217)

feat: KPI-217 sort scenarios by metric sort

---

infrastructure/network/gateways.tf
src/handlers/dynamic_report/get_dynamic_report_handler.py
src/service/calculator/calculator_repository.py
src/service/dynamic_report/dynamic_report.py
src/service/investment_peers_report/investment_repository.py
src/tests/service/dynamic_report/dynamic_report_test.py
src/tests/service/investment_peers_report/investment_repository_test.py

Reverts kpinetwork/backend#182

Revert "feat: KPI-220 refactor dynamic report"

---

src/handlers/company_details/get_company_details_handler.py
src/tests/handlers/company_details/get_company_details_handler_test.py

fix: KPI-218 fix sorting scenarios

---

infrastructure/network/gateways.tf
src/handlers/dynamic_report/get_dynamic_report_handler.py
src/service/calculator/calculator_repository.py
src/service/dynamic_report/dynamic_report.py
src/service/investment_peers_report/investment_repository.py
src/tests/data/sample_dynamic.json
src/tests/service/dynamic_report/dynamic_report_test.py
src/tests/service/investment_peers_report/investment_repository_test.py
src/utils/profile_range.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-220)

feat: KPI-220 impl dynamic report

---

src/service/metric/metric_type_service.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-246)

feat: KPI-246 new metrics sorting

---

src/handlers/investment_date_report/get_investment_date_report_handler.py
src/service/investment_date_report/investment_date_report.py
src/tests/data/sample_event_investment_date_report.json
src/tests/service/investment_date_report/investment_date_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-234)

feat: KPI-234 change function to get metric values

---

db/migrations/versions/063e82762a30_add_columns_in_metric_sort_table.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-251)
Add new columns to 'metric_sort' table

feat: KPI-251 metric sort table migration

---

infrastructure/functions/lambda.tf

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-257)

feat: KPI-257 change memory size in reports lambdas

---

src/service/company_details/company_details_service.py
src/service/metric/metric_type_service.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-250)

feat: KPI-250 refactor queries for sorting metrics

---

src/service/base_metrics/base_metrics_config_name.py
src/service/base_metrics/base_metrics_report.py
src/service/calculator/calculator_service.py
src/tests/service/base_metrics/base_metrics_report_test.py
src/tests/service/calculator/calculator_service_test.py
src/utils/app_names.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-263)

feat: KPI-263 add new metrics in by year report

---

manifest.yml
src/service/by_metric_report/by_metric_report.py
src/service/dynamic_report/dynamic_report.py
src/tests/service/dynamic_report/dynamic_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-266)

feat: KPI-266 dynamic report with new metrics sept 21

---

buildspec.yml
db/migrations/versions/27ba89d0e8d3_create_tag_model.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-270)

feat: KPI-270 add tag and company tag tables db migration

---

src/service/calculator/calculator_repository.py
src/service/company/company_service.py
src/service/edit_modify/edit_service.py
src/service/glue/update_data_service.py
src/service/investment_date_report/investment_date_repository.py
src/service/investment_peers_report/investment_options_service.py
src/service/investment_peers_report/investment_repository.py
src/service/investments/investments_service.py
src/service/scenario/delete_scenarios_service.py
src/service/upload_file/preview_data_validation_service.py
src/service/user_details/user_details_service.py
src/service/websocket/connection_service.py
src/utils/profile_range.py

We shouldn't use transaction commits for select queries, so this PR removes those lines and adds rollbacks in update/add/delete actions.

refactor: KPI-267 remove transaction commits and add rollback functions

---

infrastructure/functions/lambda.tf
infrastructure/network/gateways.tf
infrastructure/policy/iam.tf
src/handlers/users/get_users_handler.py
src/service/users/users_service.py
src/tests/data/sample_event_user.json
src/tests/handlers/users/get_users_handler_test.py
src/tests/service/users/users_service_test.py
src/utils/response_user.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-227)

feat KPI-227 improve user page pagination

---

manifest.yml
src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/by_metric_report/metric_report_repository_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-264)

Kpi 264 add new metrics in metric report

---

src/service/dynamic_report/dynamic_report.py
src/tests/service/dynamic_report/dynamic_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-266)

fix: KPI-266 delete company id from get base metrics args

---

src/handlers/comparison_vs_peers/download_comparison_vs_peers_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-268)

fix: KPI-268 add debt ebitda in download csv headers

---

src/handlers/by_metric_report/get_by_metric_report_handler.py
src/handlers/investment_date_report/get_investment_date_report_handler.py
src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/service/investment_date_report/investment_date_report.py
src/tests/service/base_metrics/base_metrics_repository_test.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/by_metric_report/metric_report_repository_test.py
src/tests/service/investment_date_report/investment_date_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-284)

feat: KPI-284 tags in by metric report

---

.github/workflows/ci-demo-kpinetwork-backend.yml

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-291)

feat: KPI-291 add truncate step

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/tags/add_tag_handler.py
src/service/tags/tags_repository.py
src/service/tags/tags_service.py
src/tests/data/sample_event_tags.json
src/tests/data/sample_response_add_tag.json
src/tests/handlers/tags/add_tag_handler_test.py
src/tests/service/tags/tags_repository_test.py
src/tests/service/tags/tags_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-273)
Add tag endpoint creation

feat: KPI-273 add tag endpoint

---

src/handlers/dynamic_report/get_dynamic_report_handler.py
src/handlers/universe_overview/get_universe_overview_handler.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-287)

feat: KPI-287 tags in universe overview report

---

.github/workflows/demo-kpinetwork-backend.yml

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-291)

fix: KPI-291 fix workflow step for production

---

src/handlers/comparison_vs_peers/get_peers_data.py
src/handlers/dynamic_report/get_dynamic_report_handler.py
src/service/base_metrics/base_metrics_report.py
src/service/by_year_report/by_year_report_service.py
src/tests/service/base_metrics/base_metrics_report_test.py
src/tests/service/by_year_report/by_year_report_service_test.py
src/tests/service/dynamic_report/dynamic_report_test.py
src/utils/app_names.py

refactor: KPI-301 refactor ranges in year report

---

src/service/base_metrics/base_metrics_config_name.py
src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/service/investment_date_report/investment_date_report.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/investment_date_report/investment_date_report_test.py
src/utils/profile_range.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-302)

feat: KPI-302 by metric report with new ranges

---

src/service/ranges/ranges_repository.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-294)
add parameter in the query to get the sorted ranges

feat: KPI-298 get all ranges endpoint order param

---

src/service/base_metrics/base_metrics_report.py
src/service/by_year_report/by_year_report_service.py
src/service/dynamic_report/dynamic_report.py
src/tests/handlers/dynamic_report/get_dynamic_report_handler_test.py
src/tests/service/dynamic_report/dynamic_report_test.py
src/utils/app_names.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-303)

refactor: KPI-303 refactor ranges in dynamic report

---

src/service/by_metric_report/by_metric_report.py
src/service/dynamic_report/dynamic_report.py
src/service/investment_date_report/investment_date_report.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/investment_date_report/investment_date_report_test.py

fix: KPI-303 fix method in dynamic report

---

src/service/base_metrics/base_metrics_config_name.py
src/service/base_metrics/base_metrics_report.py
src/service/by_metric_report/by_metric_report.py
src/service/dynamic_report/dynamic_report.py
src/service/investment_date_report/investment_date_report.py
src/service/ranges/ranges_service.py
src/tests/service/investment_date_report/investment_date_report_test.py
src/tests/service/ranges/ranges_service_test.py
src/utils/app_names.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-309)

fix: KPI-309 fix growth anonymization in reports

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/ranges/get_ranges_by_metric_handler.py
src/service/ranges/ranges_repository.py
src/service/ranges/ranges_service.py
src/tests/data/sample_event_ranges_by_metric.json
src/tests/data/sample_response_ranges_by_metric.json
src/tests/handlers/ranges/get_ranges_by_metric_handler_test.py
src/tests/service/ranges/ranges_repository_test.py
src/tests/service/ranges/ranges_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-308)

feat: KPI-308 get ranges by metric

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/ranges/modify_ranges_handler.py
src/service/ranges/ranges_repository.py
src/service/ranges/ranges_service.py
src/tests/data/sample_event_modify_ranges.json
src/tests/handlers/ranges/modify_ranges_test.py
src/tests/service/ranges/ranges_repository_test.py
src/tests/service/ranges/ranges_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-296)

feat: KPI-296 modify ranges by metric endpoint

---

infrastructure/sql/rds.tf
infrastructure/sql/variables.tf

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-207)

feat: KPI-207 change variables with new db instances

---

src/service/company_details/company_details_service.py
src/service/universe_overview/universe_overview_service.py

… overview
[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-311)

fix: KPI-311 add delete company tag subquery

---

db/migrations/versions/8311d5b9014c_alter_metric_sort_table_unique_.py

fix: KPI-290 remove unique constraint in metric sort table

---

src/service/by_year_report/by_year_report_service.py
src/tests/service/by_year_report/by_year_report_service_test.py

feat: KPI-326 add averages in year report

---

src/service/by_metric_report/by_metric_report.py
src/service/by_year_report/by_year_report_service.py
src/service/calculator/calculator_service.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/by_year_report/by_year_report_service_test.py
src/tests/service/calculator/calculator_service_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-330)

feat: KPI-330 add averages in metric report

---

db/migrations/versions/ebd63e486d09_add_column_in_time_period_table.py

feat: KPI-335 add column in time period table

---

src/service/dynamic_report/dynamic_report.py
src/tests/service/dynamic_report/dynamic_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-331)

feat: KPI-331 averages in dynamic report

---

src/handlers/scenario/add_scenario_handler.py
src/service/company_details/company_details_service.py
src/service/scenario/scenario_service.py
src/tests/service/scenario/scenario_service_test.py
src/utils/app_names.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-314)

feat: KPI-314 modify endpoints to get and add scenarios with quartes info

---

db/migrations/versions/8311d5b9014c_alter_metric_sort_table_unique_.py
db/migrations/versions/ebd63e486d09_add_column_in_time_period_table.py
src/handlers/scenario/add_scenario_handler.py
src/service/by_metric_report/by_metric_report.py
src/service/by_year_report/by_year_report_service.py
src/service/calculator/calculator_service.py
src/service/company_details/company_details_service.py
src/service/dynamic_report/dynamic_report.py
src/service/scenario/scenario_service.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/by_year_report/by_year_report_service_test.py
src/tests/service/calculator/calculator_service_test.py
src/tests/service/dynamic_report/dynamic_report_test.py
src/tests/service/scenario/scenario_service_test.py
src/utils/app_names.py

release: KPI-335 KPI-330 modify time period table and add averages in report

---

etl/kpinetwork_analizer.py

Modify insert data functions in script to consider quarters
[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-317)

refactor: KPI-317 modify insert data functions in script

---

infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
src/handlers/company_details/get_full_year_total_handler.py
src/service/company_details/company_details_service.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-343)

fix: KPI-343 add company id path parameter

---

etl/kpinetwork_analizer.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-318)

refactor: KPI-318 refactor glue script to update data with periods

---

src/service/base_metrics/base_metrics_repository.py
src/tests/service/base_metrics/base_metrics_repository_test.py
src/tests/service/dynamic_report/dynamic_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-336)

feat: KPI-336 refactor year report to consider full year

---

src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/by_metric_report/metric_report_repository_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-337)

feat: KPI-337 by metric report get full year

---

src/service/base_metrics/base_metrics_repository.py
src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-337)

fix: KPI-337 change get years query in by metric report

---

infrastructure/buckets/outputs.tf
infrastructure/buckets/s3.tf
infrastructure/functions/lambda.tf
infrastructure/functions/outputs.tf
infrastructure/logs/cloudwatch.tf
infrastructure/network/gateways.tf
infrastructure/network/outputs.tf
infrastructure/policy/iam.tf
infrastructure/policy/outputs.tf
infrastructure/variables.tf
manifest.yml
src/handlers/company_details/get_full_year_total_handler.py
src/handlers/scenario/add_scenario_handler.py
src/service/base_metrics/base_metrics_repository.py
src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/service/company_details/company_details_service.py
src/service/dynamic_report/dynamic_report.py
src/service/scenario/scenario_service.py
src/tests/data/sample_event_get_full_year_total.json
src/tests/handlers/company_details/get_full_year_total_handler_test.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/by_metric_report/metric_report_repository_test.py
src/tests/service/company_details/company_details_service_test.py
src/tests/service/dynamic_report/dynamic_report_test.py
src/tests/service/scenario/scenario_service_test.py
src/utils/app_names.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-343)

release: KPI-343 KPI-317 KPI-318 full year endpoint and glue script refactor

---

infrastructure/network/gateways.tf
src/handlers/quarters_report/get_quarters_report_handler.py
src/service/quarters_report/quarters_report.py
src/service/quarters_report/quarters_report_repository.py
src/tests/service/quarters_report/quarters_report_repository_test.py
src/tests/service/quarters_report/quarters_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-346)

feat: KPI-346 year to date quarters report

---

manifest.yml
src/service/quarters_report/quarters_report.py
src/service/quarters_report/quarters_report_repository.py
src/tests/service/quarters_report/quarters_report_repository_test.py
src/tests/service/quarters_report/quarters_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-345)

feat: KPI-345 add last twelve months

---

pyproject.toml
src/service/quarters_report/quarters_report.py
src/tests/service/quarters_report/quarters_report_repository_test.py
src/tests/service/quarters_report/quarters_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-347)

fix: KPI-347 fix anonymization method and vs calculation

---

src/service/by_metric_report/by_metric_report.py
src/service/quarters_report/quarters_report.py
src/tests/service/by_metric_report/by_metric_report_test.py

fix: KPI-350 fix company name anonymization

---

src/service/by_metric_report/metric_report_repository.py
src/service/quarters_report/quarters_report.py
src/service/quarters_report/quarters_report_repository.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-348)

fix: KPI-348 add company tag and tag joins

---

src/service/quarters_report/quarters_report.py
src/tests/service/quarters_report/quarters_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-350)

fix: KPI-350 fix ltm update of quarters when there is no full year

---

src/service/dynamic_report/dynamic_report.py

fix: KPI-348 fix dynamic report

---

src/service/dynamic_report/dynamic_report.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-350)

release: KPI-350 fix dynamic report

---

src/service/investment_date_report/investment_date_report.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-350)

fix: KPI-350 fix investment date report anonymization

---

src/service/dynamic_report/dynamic_report.py
src/service/investment_date_report/investment_date_report.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-350)

release: KPI-350 hotfix investment date anonymization

---

src/service/quarters_report/quarters_report.py
src/service/quarters_report/quarters_report_repository.py
src/tests/service/quarters_report/quarters_report_repository_test.py
src/tests/service/quarters_report/quarters_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-356)

fix: KPI-356 fix actuals plus budget ltm average

---

src/handlers/quarters_report/get_quarters_report_handler.py
src/service/quarters_report/quarters_report.py
src/tests/service/quarters_report/quarters_report_test.py

[Go to Jira](https://kpinetwork.atlassian.net/browse/KPI-354)

feat: KPI-354 quarters report No standard metrics

---

src/service/by_metric_report/by_metric_report.py
src/service/by_metric_report/metric_report_repository.py
src/service/dynamic_report/dynamic_report.py
src/service/quarters_report/quarters_report.py
src/service/quarters_report/quarters_report_repository.py
src/tests/service/by_metric_report/by_metric_report_test.py
src/tests/service/quarters_report/quarters_report_repository_test.py
src/tests/service/quarters_report/quarters_report_test.py
src/utils/app_names.py

fix: KPI-354 355 356 no standard metrics in quarters report, LTM averages and averages

---

src/service/quarters_report/quarters_report_repository.py

fix: KPI-354 fix quarter reports with multiple tags
